export default[
    {
        id:1,
        brand: "Power Cable ",
        img: "CCTV1.jpg",
        type: "Hardware Accessories",        
    },
    {
        id:2,
        brand: "Power Supply",
        img: "DVR1.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:3,
        brand: "Laptop Charger",
        img: "IPCam1.jpg",
        type: "Hardware Accessories",       
    },
    {
        id:4,
        brand: "Laptop Battery",
        img: "NVR1.jpg",
        type: "Hardware Accessories",       
    },
    {
        id:5,
        brand: "RAM",
        img: "Accounts.jpg",
        type: "Hardware Accessories",        
    },
    {
        id:6,
        brand: "SSD",
        img: "DELL.png",
        type: "Hardware Accessories",          
    },
    {
        id:7,
        brand: "HDD",
        img: "DELL.png",
        type: "Hardware Accessories",          
    },
    {
        id:8,
        brand: "Pen Drive",
        img: "DELL.png",
        type: "Hardware Accessories",          
    },
    {
        id:9,
        brand: "CPU Cooling Fan",
        img: "DELL.png",
        type: "Hardware Accessories",          
    },
    {
        id:10,
        brand: "Router",
        img: "CCTV1.jpg",
        type: "Network  Accessories",        
    },
    {
        id:11,
        brand: "Switch",
        img: "DVR1.jpg",
        type: "Network  Accessories",          
    },
    {
        id:12,
        brand: "RJ45 Connector",
        img: "IPCam1.jpg",
        type: "Network  Accessories",       
    },
    {
        id:13,
        brand: "RACK",
        img: "NVR1.jpg",
        type: "Network  Accessories",       
    },
    {
        id:14,
        brand: "Patch Cord",
        img: "Accounts.jpg",
        type: "Network  Accessories",        
    },
    {
        id:15,
        brand: "Patch Panel",
        img: "DELL.png",
        type: "Network  Accessories",          
    },
    {
        id:16,
        brand: "CAT 6 UTP Cable",
        img: "DELL.png",
        type: "Network  Accessories",          
    },
    {
        id:17,
        brand: "MC",
        img: "DELL.png",
        type: "Network  Accessories",          
    },
    {
        id:18,
        brand: "SFP Module",
        img: "DELL.png",
        type: "Network  Accessories",          
    },
    {
        id:19,
        brand: "Crimper",
        img: "CCTV1.jpg",
        type: "Network  Accessories",        
    },
    {
        id:20,
        brand: "Cable Manager",
        img: "DVR1.jpg",
        type: "Network  Accessories",          
    },
    {
        id:21,
        brand: "Fiber Cable",
        img: "IPCam1.jpg",
        type: "Fiber   Accessories",       
    },
    {
        id:22,
        brand: "ODF",
        img: "NVR1.jpg",
        type: "Fiber Accessories",       
    },
    {
        id:23,
        brand: "Patch cord",
        img: "Accounts.jpg",
        type: "Fiber Accessories",        
    },
    {
        id:24,
        brand: "Patch Panel",
        img: "DELL.png",
        type: "Fiber Accessories",          
    },
    {
        id:25,
        brand: "Pick tail",
        img: "DELL.png",
        type: "Fiber Accessories",          
    },
    {
        id:26,
        brand: "SFP",
        img: "DELL.png",
        type: "Fiber Accessories",          
    },
    {
        id:27,
        brand: "MC",
        img: "DELL.png",
        type: "Fiber Accessories",          
    }
]