export default[
    {
        id:1,
        brand: "Power Cable ",
        img: "Power Cable.jpg",
        type: "Hardware Accessories",        
    },
    {
        id:2,
        brand: "Power Supply",
        img: "Power Supply.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:3,
        brand: "Laptop Charger",
        img: "Laptop Charger.jpg",
        type: "Hardware Accessories",       
    },
    {
        id:4,
        brand: "Laptop Battery",
        img: "Laptop Battery.jpg",
        type: "Hardware Accessories",       
    },
    {
        id:5,
        brand: "RAM",
        img: "RAM.jpg",
        type: "Hardware Accessories",        
    },
    {
        id:6,
        brand: "SSD",
        img: "SSD.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:7,
        brand: "HDD",
        img: "HDD.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:8,
        brand: "Pen Drive",
        img: "Pen Drive.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:9,
        brand: "CPU Cooling Fan",
        img: "CPU Cooling Fan.jpg",
        type: "Hardware Accessories",          
    },
    {
        id:10,
        brand: "Router",
        img: "Router.jpg",
        type: "Network  Accessories",        
    },
    {
        id:11,
        brand: "Switch",
        img: "Switch.jpg",
        type: "Network  Accessories",          
    },
    {
        id:12,
        brand: "RJ45 Connector",
        img: "RJ45 Connector.jpg",
        type: "Network  Accessories",       
    },
    {
        id:13,
        brand: "RACK",
        img: "RACK.jpg",
        type: "Network  Accessories",       
    },
    {
        id:14,
        brand: "Patch Cord",
        img: "Patch Cord.jpg",
        type: "Network  Accessories",        
    },
    {
        id:15,
        brand: "Patch Panel",
        img: "Patch Panel.jpg",
        type: "Network  Accessories",          
    },
    {
        id:16,
        brand: "CAT 6 UTP Cable",
        img: "CAT 6 UTP Cable.jpg",
        type: "Network  Accessories",          
    },
    {
        id:17,
        brand: "MC",
        img: "MC.jpg",
        type: "Network  Accessories",          
    },
    {
        id:18,
        brand: "SFP Module",
        img: "SFP Module.jpg",
        type: "Network  Accessories",          
    },
    {
        id:19,
        brand: "Crimper",
        img: "Crimper.jpg",
        type: "Network  Accessories",        
    },
    {
        id:20,
        brand: "Cable Manager",
        img: "Cable Manager.jpg",
        type: "Network  Accessories",          
    },
    {
        id:21,
        brand: "Fiber Cable",
        img: "IPCam1.jpg",
        type: "Fiber   Accessories",       
    },
    {
        id:22,
        brand: "ODF",
        img: "ODF.jpg",
        type: "Fiber Accessories",       
    },
    {
        id:23,
        brand: "Patch cord",
        img: "Patch cord.jpg",
        type: "Fiber Accessories",        
    },
    {
        id:24,
        brand: "Patch Panel",
        img: "Patch Panel.jpg",
        type: "Fiber Accessories",          
    },
    {
        id:25,
        brand: "Pigtail",
        img: "Pigtail.jpg",
        type: "Fiber Accessories",          
    },
    {
        id:26,
        brand: "SFP",
        img: "SFP Module.jpg",
        type: "Fiber Accessories",          
    },
    {
        id:27,
        brand: "MC",
        img: "MC.jpg",
        type: "Fiber Accessories",          
    }
]